// Generated by IB v0.2.10 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation Camera

@end


@implementation ParserError

@end


@implementation NSNotificationCenter

@end


@implementation NSURLRequest

@end


@implementation UIView

@end


@implementation UIViewController

@end


@implementation Response

@end


@implementation Query

@end


@implementation InvalidURLError

@end


@implementation InvalidFileError

@end


@implementation LoginViewController

@end


@implementation ProfileViewController

@end


@implementation ProjectsTableViewController

@end


@implementation RecentTableViewController

@end


@implementation Build

@end


@implementation Circle

@end


@implementation Me

@end


@implementation Project

@end


@implementation BuildViewCell

@end


@implementation ProjectViewCell

@end



