// Generated by IB v0.2.10 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>
#import <UIKit/UIKit.h>

@interface Camera





-(IBAction) initialize:(id) location;
-(IBAction) location;
-(IBAction) imagePickerControllerDidCancel:(id) picker;
-(IBAction) picker;
-(IBAction) dismiss;
-(IBAction) camera_device;
-(IBAction) media_type_to_symbol:(id) media_type;
-(IBAction) symbol_to_media_type:(id) symbol;
-(IBAction) error:(id) type;

@end


@interface ParserError: StandardError







@end


@interface NSNotificationCenter





-(IBAction) observers;
-(IBAction) unobserve:(id) observer;

@end


@interface NSURLRequest





-(IBAction) to_s;

@end


@interface UIView





-(IBAction) handle_gesture:(id) recognizer;

@end


@interface UIViewController





-(IBAction) content_frame;

@end


@interface Response





-(IBAction) initialize:(id) values;
-(IBAction) update:(id) values;
-(IBAction) to_s;
-(IBAction) update_status_description;

@end


@interface Query





-(IBAction) to_s;
-(IBAction) connectionDidFinishLoading:(id) connection;
-(IBAction) create_request;
-(IBAction) set_content_type;
-(IBAction) create_request_body;
-(IBAction) append_payload:(id) body;
-(IBAction) append_form_params:(id) body;
-(IBAction) append_files:(id) body;
-(IBAction) append_body_boundary:(id) body;
-(IBAction) create_url:(id) url_string;
-(IBAction) validate_url:(id) url;
-(IBAction) escape:(id) string;
-(IBAction) convert_payload_to_url;
-(IBAction) log:(id) message;
-(IBAction) escape_line_feeds:(id) hash;
-(IBAction) patch_nsurl_request:(id) request;
-(IBAction) call_delegator_with_response;

@end


@interface InvalidURLError: StandardError







@end


@interface InvalidFileError: StandardError







@end


@interface LoginViewController: UIViewController

@property IBOutlet id input_field;
@property IBOutlet UIButton * sign_in_btn;



-(IBAction) viewDidLoad;
-(IBAction) viewDidUnload;
-(IBAction) shouldAutorotateToInterfaceOrientation:(id) interfaceOrientation;
-(IBAction) sign_in:(id) sender;
-(IBAction) alert_error;
-(IBAction) textFieldShouldReturn:(id) text_field;
-(IBAction) textFieldFinished:(id) sender;

@end


@interface ProfileViewController: UIViewController

@property IBOutlet id profile_image_view;
@property IBOutlet id email_label;
@property IBOutlet id token_label;



-(IBAction) viewDidLoad;
-(IBAction) viewDidUnload;
-(IBAction) shouldAutorotateToInterfaceOrientation:(id) interfaceOrientation;
-(IBAction) gravatar;
-(IBAction) gravatar_host;

@end


@interface ProjectsTableViewController: UITableViewController





-(IBAction) viewDidLoad;
-(IBAction) viewDidUnload;
-(IBAction) load_projects;
-(IBAction) shouldAutorotateToInterfaceOrientation:(id) interfaceOrientation;
-(IBAction) numberOfSectionsInTableView:(id) tableView;
-(IBAction) refresh;
-(IBAction) pullToRefreshViewDidStartLoading:(id) view;

@end


@interface RecentTableViewController: UITableViewController





-(IBAction) viewDidLoad;
-(IBAction) viewDidUnload;
-(IBAction) load_recent_builds;
-(IBAction) check_for_rewards:(id) builds;
-(IBAction) viewDidAppear:(id) animated;
-(IBAction) shouldAutorotateToInterfaceOrientation:(id) interfaceOrientation;
-(IBAction) numberOfSectionsInTableView:(id) tableView;
-(IBAction) refresh;
-(IBAction) pullToRefreshViewDidStartLoading:(id) view;

@end


@interface Build





-(IBAction) initialize:(id) attrs;
-(IBAction) username;
-(IBAction) status_color;
-(IBAction) check_first_passing:(id) info;

@end


@interface Circle





-(IBAction) initialize;
-(IBAction) default_headers;

@end


@interface Me





-(IBAction) initialize:(id) attrs;
-(IBAction) token;

@end


@interface Project





-(IBAction) initialize:(id) attrs;
-(IBAction) all_branches;
-(IBAction) branch_name;
-(IBAction) repo_name;

@end


@interface BuildViewCell: UITableViewCell

@property IBOutlet id build_label;
@property IBOutlet id status_view;
@property IBOutlet id subject_label;
@property IBOutlet id committer_label;





@end


@interface ProjectViewCell: UITableViewCell

@property IBOutlet id name_label;
@property IBOutlet id branch_label;
@property IBOutlet id build1_view;
@property IBOutlet id build2_view;
@property IBOutlet id build3_view;



-(IBAction) setup_build_views:(id) project;

@end



